# Generated by Django 2.2.6 on 2019-10-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0007_homepagecarouselimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarouselimage',
            name='carousel_images',
        ),
        migrations.AddField(
            model_name='homepagecarouselimage',
            name='carousel_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
