# Generated by Django 2.2.6 on 2019-10-09 06:13

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191007_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_image', to='home.HomePage'),
        ),
    ]
